content:
  - name: soveltamisohjeet
    label: soveltamisohjeet
    type: collection
    path: content/soveltamisohje
    subfolders: true
    filename: '{primary}.md'
    extensions: [md]
    view:
      sort: [filename]
      default:
        sort: filename
        order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
